from typing import Protocol

from app.models import Segment


class VideoSource(Protocol):
    def list_cameras(self) -> list[dict]: ...
    def candidates(
        self, labels: set[str], camera_ids: list[str] | None, segment_ids: list[str] | None
    ) -> list[Segment]: ...
    def get_segment(self, segment_id: str) -> Segment: ...
    def text_search(self, query: str, k: int = 200) -> list[tuple[str, float]]: ...  # (segment_id, score)
    def ask(self, segment_id: str, question: str) -> str: ...
    def clip_url(self, segment_id: str) -> str: ...
    def frame_url(self, segment_id: str, t: float = 0.5) -> str: ...
